### ISSUE TITLE
Mario & Luigi Super Star Saga + Bowser's Minions  EXP not working for Luigi

### ISSUE THREAD

**Issue by SAIYAN48** [JourneyOver/CTRPF-AR-CHEAT-CODES#12]
## Checklist:

- [x] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [ ] Other

## Description

When the cheat is active, only Mario can get the exp boost and not Luigi.
## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [e.g. New 3DS, Old 3DS, 2DS]
New 3DS XL
**3DS Firmware Version:** [e.g. 11.6.0-39E]
11.6.0-39U
**Method Used:** [e.g. LUMAS3DS 9.0 Plugin Loader, BOOTNTR]
LUMAS3DS 9.0 Plugin Loader
**Game Version:** [e.g. 1.0, 1.1]
I think there's only the one... so latest.

**Language & Region:** [e.g. English & USA]
English & USA

**Comment by JourneyOver** [comment]
Will take a look into this soonish. 

Are you sure you are doing the correct button combo?
R+down for Mario
R+Up for Luigi

**Comment by SAIYAN48** [comment]
Yes. R+Down works fine, its the R+UP that does nothing.

**Comment by jmapjp** [comment]
Try the new edit..it should work now

**Comment by JourneyOver** [comment]
TBH I totally forgot all about this as I've been very busy xD I went ahead and merged your fix @jmapjp so let's hope it works for him.

**Comment by jmapjp** [comment]
Yeah I just saw this issue and tested it...and it really wasn't working...which was weird since it was when I first made that code. So I just edited a line or two..it turns out the issue was that the address the code was pointing to, wasn't getting affected for some reason.

**Comment by SAIYAN48** [comment]
I'll test it in a bit.

**Comment by SAIYAN48** [comment]
Yep, works now. Thanks guys!

**Comment by JourneyOver** [comment]
Glad to hear :)

**Comment by jmapjp** [comment]
Mission Accomplished
