### ISSUE TITLE
Cleanup GB(C)(A) injects/VC games + remove spam codes & codes that require having to read things on fort42

### ISSUE THREAD

**Issue by JourneyOver** [JourneyOver/CTRPF-AR-CHEAT-CODES#17]
Need to run through GB(C)(A) games at some point and figure out which are injects and which are VC games and mark them accordingly.

**Comment by jmapjp** [comment]
The one I just put was the official Vc from eshop

**Comment by JourneyOver** [comment]
Yea I know I marked it accordingly :P this is just for a general reminder for myself which hopefully I won't forget about xD

**Comment by jmapjp** [comment]
Oh I got it..."the smallest pencil is better than the longest memory"

**Comment by jmapjp** [comment]
You could use free shop to cross-reference...what ever isn't there would be an inject

**Comment by JourneyOver** [comment]
I'm using the 3DS title key site, along with http://www.3dsdb.com/ and freeshop so cross referencing three different sites xD

**Comment by jmapjp** [comment]
Perfect...doesn't get better than that
