### ISSUE TITLE
Fix The README

### ISSUE THREAD

**Issue by JedVermil** [JourneyOver/CTRPF-AR-CHEAT-CODES#2]
I just Noticed your README about USING BOOTNTR, The Step#3 Should look like this;
3.Place the contents from CTRPluginFramework - Action Replay.7z into SD:/plugin/<Title ID of the game folder>/

**Comment by JedVermil** [comment]
Oh, and you should add this to the very first step of USING BOOTNTR;
1.Make sure That Disable the Plugin Loader from the Rosalina Menu if Your using the boot.firm of Luma3DS 9.0 Plugin Loader.
2.Only BOOTNTR 3.3 Works if Your using the boot.firm of Luma3DS 9.0 Plugin Loader.

**Comment by JourneyOver** [comment]
Oh shit I missed that when I was setting up the BOOTNTR steps as I mainly just copied everything from "Using LUMAS3DS 9.0 Plugin Loader" and just edited what I needed to but I guess I missed something >..< and the steps for using BOOTNTR is mainly for people who are not using the Luma3DS 9.0 Plugin Loader but using the default Luma3DS

**Comment by JourneyOver** [comment]
Fixed in 1caba66eac2c738017ccad440b8fea9a2bf0fff5 cc2c948f8f964ef409b540884375fcff8f9f4d62 and 6cb9105e17abb9ba08bb9503deae2f2143cc1462 .. Took me 3 commits to fix mistakes in the readme xD

Thanks for noticing the issue ^^

**Comment by JourneyOver** [comment]
if you end up noticing anymore let me know :) I'll still get notifications from a closed issue.

**Comment by JedVermil** [comment]
Add these to your notes;
1. `LUMA3DS 9.0 Plugin Loader` only recognises `CTRPF (AR) Plugins` called `plugin.plg`
2.Make sure your using only `1 CTRPF (AR) Plugin`! And No Other Plugins included alongside it! (Such as `Gateshark2NTR`, `libshark2NTR` or any other `Plugins`).
3.If it gives you error,Try Deleting the `CTRPFData.bin` if it exists.

**Comment by JourneyOver** [comment]
Done, I switched notes for FAQs during the update as well and added a couple more things.

**Comment by JedVermil** [comment]
Aren't you gonna replace those .rar(s) on your README into .zip?
Example;
1.Download `Luma3DS 9.0 - Plugin loader.rar` & `ActionReplay.rar`
Into
1.Download `Luma3DS 9.0 - Plugin loader.zip` & `ActionReplay.zip`

**Comment by JourneyOver** [comment]
Oooof change one thing forget another >...< yea give me a moment lmao..

**Comment by JourneyOver** [comment]
Fixed in https://github.com/JourneyOver/CTRPF-AR-CHEAT-CODES/commit/ec71376f2f7ee016e065ed950019e7d428014df8 Thanks for reminding me!

**Comment by JedVermil** [comment]
Oops! Didn't noticed that you already added my `How to` to your README.
I actually updated my `How to`  a minutes ago, sorry... Please update README again. Thanks^^

**Comment by JourneyOver** [comment]
hehe :p will get it updated in a moment.

**Comment by JourneyOver** [comment]
Updated in https://github.com/JourneyOver/CTRPF-AR-CHEAT-CODES/commit/5b29778fe7867fbc3e4f9a2239aa54123a2f1773
