### ISSUE TITLE
Mario Tennis Open cheat file not detected and Starfox 64 3D cheat freezes the game when the plugin is opened to pick cheats

### ISSUE THREAD

**Issue by RandomMan25XX** [JourneyOver/CTRPF-AR-CHEAT-CODES#21]
## Checklist:

- [x] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [ ] Other

## Description

Trying to load cheats for Starfox freezes the game but the audio continues and Mario Tennis Open loads the plugin (because the screen flashes green) but the plugin doesn't load or find the cheat file
## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [e.g. New 3DS, Old 3DS, 2DS]
Old 3DS
**3DS Firmware Version:** [e.g. 11.6.0-39E]
11.6.0-39U
**Method Used:** [e.g. LUMAS3DS 9.0 Plugin Loader, BOOTNTR]
Luma 3DS Plugin Loader
**Game Version:** [e.g. 1.0, 1.1]
1.0
**Language & Region:** [e.g. English & USA]
English & USA

**Comment by JourneyOver** [comment]
I'll look into the starfox issue when I have time, as for the mario tennis open, make sure you are download the file correctly and placing it in the correct location.

*Note: right click and doing a "save as" on the .txt file does not work as expected anymore due to changes with github. If this is how you are downloading the file then what you will have to do is go further in to the actual raw page before you do a right click "save as".

**Comment by RandomMan25XX** [comment]
I just downloaded the entire cheat pack and pick and choose based on which games I have, everything is in the correct place as it should, everything but mario tennis finds the required text file and plugin specific to that game

**Comment by JourneyOver** [comment]
Hmm alright, I'll take a look.

**Comment by JourneyOver** [comment]
Okay so I took a look at both starfox 64 3D and Mario Tennis Open.

For starfox there is sadly nothing I can do, as it seems that the plugin is just broken for that game I even tried going code by code to see if I could find a culprit and everything came back with just a freeze. So you'll either have to wait for someone to come around to fix up the codes or fix them yourself some how. (I'm leaving the file in my repo but with a note in the txt file that it's currently broken)

As for Mario Tennis Open, try using the `ActionReplay_Alt` version and it should now load up the plugin for you correctly.
