### ISSUE TITLE
 ActionReplay.plg blocking n3DS built in circle-pad pro [instead of wifi?]

### ISSUE THREAD

**Issue by iSharingan** [JourneyOver/CTRPF-AR-CHEAT-CODES#25]
I'm assuming it was intended to block wifi/online access with cheats active, but currently all the plugin really does is forcibly disable the n3DS' built-in circle-pad pro. In MH4U/MHGen, you just get an in game 'announcement'/error that the circle-pad connection has been lost, plus various settings are forced back to default. In most other games like MH Stories its only apparent as the secondary camera controls don't work while the ZL/ZR buttons dont function.

if you need more device specifics I can provide them but I doubt its entirely needed. I can contact Nanquitas directly if needed (I'm in his Discord group, among other contact options).

**Comment by JourneyOver** [comment]
For `ActionReplay` and `Luma3DS 9.0 - Plugin Loader` stuff please redirect your issues to http://gbatemp.net/threads/ctrpluginframework-blank-plugin.487729/ or contact @Nanquitas on his discord group for help as I am not the one who created them so I can not help you with these two things, sorry.

One thing I could suggest is to try the `ActionReplay_ALT` version and see if that does the same thing or not, but other than that you'll need to contact Nanquitas either through his thread on GBATemp or discord for help.

Closing this issue as it's something I can't fix personally.

**Comment by iSharingan** [comment]
understood. just wasn't sure if you were one of the others in the discord helping work on the plugin.

**Comment by JourneyOver** [comment]
Nope I didn't help create the plugin or anything. I'm just someone hosting a bunch of codes that people have made over time xD

**Comment by iSharingan** [comment]
apparently wifi blocking wasn't added (though the bug is known). there's actually a 'fix' in that very thread, too. Posting here for others coming across it:

Open Rosalina menu (L+Down+Select by default)
Select 'Miscellaneous Options...'
Select 'Start InputRedirection'

**Comment by JourneyOver** [comment]
Thanks. I'll add the tip to the readme when I am able to get around to revamping the readme a bit.
