### ISSUE TITLE
help

### ISSUE THREAD

**Issue by AgentScarlet** [JourneyOver/CTRPF-AR-CHEAT-CODES#39]
says no cheats for alliace alive. i know i got it in the right area. the cheats folder is on root. the luma payloader where this site says to put and so is the actionreplay.plg file. so tell me pls what am i doing wrong

**Comment by JourneyOver** [comment]
1. is your firmware 11.4 or higher?

2. Make sure you are downloading the txt file for your region.

3. Get pictures of your root, cheats, and luma folder so I can see exactly how your folder layouts are.

**Comment by MrHaqs** [comment]
You can close this issue. I've sorted this out on GBAtemp

**Comment by JourneyOver** [comment]
Great, thanks for letting me know @MrHaqs :)
