### ISSUE TITLE
Trying House Modifier Code

### ISSUE THREAD

**Issue by Kimmi1989** [JourneyOver/CTRPF-AR-CHEAT-CODES#40]
How do you activate the house modifier code?

**Comment by JourneyOver** [comment]
From looking at the code it looks to be one that you'll have to change the value for in the .txt file.. Sadly I do not know the values to change it for that so I may end up removing the code along with a few others that are like this that I see in the same .txt file.

Going to close this as there is nothing really that I can do myself other than removing said code from the .txt file
