### ISSUE TITLE
New Cheats (Dragon Quest Monsters Joker 3 (JPN))

### ISSUE THREAD

**Issue by SanktyRG** [JourneyOver/CTRPF-AR-CHEAT-CODES#45]
## Checklist:

- [ ] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [x] Other

## Description
Hello, I just finally finished fixing and writting cheats for DQMJ3 english translation:

[(SELECT+Y) MAX Money v1.1]
DD000000 00000804
D3000000 00000000
B07E69B0 00000000
B0000008 00000000
B0000004 00000000
000000CC 000F423F
D0000000 00000000

[Skill Points 999 v1.1]
D3000000 00000000
0071F2A0 E92D4002
0071F2A4 E5901000
0071F2A8 E3A00FFA
0071F2AC E2400001
0071F2B0 E1C103BA
0071F2B4 E8BD8002
0061C7FC EA040AA7

[100% Capture v1.1]
D3000000 00000000
005A19E4 E3A00FFA

[Always preemptive attack v1.1]
D3000000 00000000
005A27AC EA000022

[EXP multiplier after battle x1 v1.1]
D3000000 00000000
003A16B4 E0844000

[EXP multiplier after battle x2 v1.1]
D3000000 00000000
003A16B4 E0844080

[EXP multiplier after battle x4 v1.1]
D3000000 00000000
003A16B4 E0844100

[EXP multiplier after battle x8 v1.1]
D3000000 00000000
003A16B4 E0844180

[EXP multiplier after battle x16 v1.1]
D3000000 00000000
003A16B4 E0844200

[EXP multiplier after battle x32 v1.1]
D3000000 00000000
003A16B4 E0844280

[EXP multiplier after battle x64 v1.1]
D3000000 00000000
003A16B4 E0844300

[GOLD Multiplier after battle x1 v1.1]
D3000000 00000000
003A17D4 E0855000

[GOLD Multiplier after battle x2 v1.1]
D3000000 00000000
003A17D4 E0855080

[GOLD Multiplier after battle x4 v1.1]
D3000000 00000000
003A17D4 E0855100

[GOLD Multiplier after battle x8 v1.1]
D3000000 00000000
003A17D4 E0855180

[GOLD Multiplier after battle x16 v1.1]
D3000000 00000000
003A17D4 E0855200

[GOLD Multiplier after battle x32 v1.1]
D3000000 00000000
003A17D4 E0855280

[GOLD Multiplier after battle x64 v1.1]
D3000000 00000000
003A17D4 E0855300

[Standby monsters get same amount EXP v1.1]
D3000000 00000000
002EC4BC E3A09001

[Deposit monsters get same amount EXP v1.1]
D3000000 00000000
002EC5EC E3A09001

[Always Critical attack v1.1]
D3000000 00000000
0071F2C0 E2460010
0071F2C4 E3500004
0071F2C8 31A04384
0071F2CC E1A00007
0071F2D0 E12FFF1E
0058F084 EB06408D
00599698 EB061708

[Can act twice in one turn v1.1]
D3000000 00000000
0071F300 E5D4B004
0071F304 E24BB010
0071F308 E35B0004
0071F30C 3A000001
0071F310 E3550000
0071F314 EAF9B5BB
0071F318 E3A08002
0071F31C E1500000
0071F320 EAFFFFFB
0058CA04 EA064A3D

[Make the size of all monsters one v1.1]
D3000000 00000000
0061D44C EA000015
002301CC EA0001BC

[Infinite air jump v1.1]
D3000000 00000000
001CDDC8 E1A00000

[Producing accessories doesn't use materials v1.1]
D3000000 00000000
00627734 E3A00000
0062773C E1C600B2

[When fusing, All skills are selectable v1.1]
D3000000 00000000
E071F340 00000030
E35500F7 02855004
E2450C01 E3500025
02855006 E3500091
02855009 E35000BB
02855001 E35000CE
02855017 E35000FB
0071F370 EAF8A4B2
005485BC E2850001
0054863C EA075B3F

[Fusion is possible from LV1 v1.1]
D3000000 00000000
001F8B78 E3500001
001F8B88 E3500001
001FB02C E3500001
001FB03C E3500001
0027B114 E3500001
002D352C E3500001
00373D80 E3500001
00373DD8 E3500001
004F9408 E3500001
0057F8D4 E3500001
0057FA40 E3500001
006B24DC E3500001
006B24EC E3500001

[Fusing monsters will not vanish v1.1]
D3000000 00000000
E071F380 00000030
E59F1024 E5911000
E5911008 E5911004
E59F3018 E0813003
E5931000 E3510000
028EE024 E3A03001
E12FFF1E 007E69B0
0071F3B0 0001CEBC
00525258 EB07E848

[Monster always drop items after battle v1.1]
D3000000 00000000
E071F410 00000030
E3500000 0A000007
E59D302C E59D1060
E0812083 E2833001
E59F100C E18100B2
E6BF0073 E58D002C
EAFA14F1 001162A6
005A47F4 EA05EB05
005A47DC E3A00001
005A4850 E3A00001

[Fusion can inherit 6 skills v1.1]
D3000000 00000000
001F77F8 EA00001E

[Get all items at maximum number v1.1]
D3000000 00000000
00279C84 E3A02FFA
00279C88 EBFE502B
00279C8C EA000000

[Automatically pick up an item on the ground v1.1]
D3000000 00000000
005F8518 E1A00000

[Always exercises ability to sometimes exercise v1.1]
D3000000 00000000
0071F440 E92D401E
0071F444 E2424010
0071F448 E3540004
0071F44C 33A00001
0071F450 38BD801E
0071F454 EBF9D26C
0071F458 E8BD801E
00592220 EB063486
005A2724 E1A00000

I know there is a plg plugin but not an NTR text file for Luma+Rosalina, I found the cheats and arranged them in a txt file, I can confirm the cheats work perfectly on the translated version of the game.

**Comment by Volcannon** [comment]
These codes do not work/cause the game to crash.

**Comment by Kryod** [comment]
I confirm, none of these codes work and often crashes the game.
