### ISSUE TITLE
WarioWare Gold (EUR) (00040000001D1C00)

### ISSUE THREAD

**Issue by Korados** [JourneyOver/CTRPF-AR-CHEAT-CODES#50]
## Checklist:

- [x] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [ ] Other

## Description

I'm sorry to bother you again but WarioWare Gold had an update to Ver. 1.1
and now three of the codes in the database don't work anymore.
These are the 99 Points in Wario Kard and Infinite Lives On/Off codes.
Only the money code still works.
## Extra Information
New 3DS
11.8.0-41E
Luma 9.1 Rosalina menu or Plugin loader
Ver. 1.1
EUR

**Comment by JourneyOver** [comment]
It's fine lol

Thanks for the report, when I get my new computer (hopefully this weekend) I will update the cheat names to reflect the version 1.0 codes vs the codes that work for both 1.0 and 1.1.

**Comment by JourneyOver** [comment]
No close
