### ISSUE TITLE
RetroArch Emulator Issue

### ISSUE THREAD

**Issue by Smoker1** [JourneyOver/CTRPF-AR-CHEAT-CODES#54]
## Checklist:

- [ ] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [x ] Other

## Description
System Crashes when trying to run ANY RetroArch Core with the Action Replay Plugin Enabled to create Cheats. Main Goal is to try to create Cheats for FBA2012, since they are not Implemented yet. I can get Cheats created on my O3DS (slow Process due to the Frame-rate). Cheats will not work under Rosalina Cheat System, no matter what boot.firm I use.

## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [e.g. New 3DS, Old 3DS, 2DS] N3DS

**3DS Firmware Version:** [e.g. 11.6.0-39E] Luma3DS 11.8 (Latest)

**Method Used:** [e.g. LUMAS3DS 9.0 Plugin Loader, BOOTNTR] Luma3DS, Plugin Loader

**Game Version:** [e.g. 1.0, 1.1] 31 October Nightly RetroArch

**Language & Region:** [e.g. English & USA]

**Comment by JourneyOver** [comment]
Not something I can fix as I'm not the one who made the action replay plugin, this is something you'd have to bring up with nanquitas on gbatemp as he is the one who made it.
