### ISSUE TITLE
bravely default no one of this cheats work just close the citra 

### ISSUE THREAD

**Issue by hyunzdk** [JourneyOver/CTRPF-AR-CHEAT-CODES#55]
## Checklist:

- [ ] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [ ] Other

## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [e.g. New 3DS, Old 3DS, 2DS]

**3DS Firmware Version:** [e.g. 11.6.0-39E]

**Method Used:** [e.g. LUMAS3DS 9.0 Plugin Loader, BOOTNTR]

**Game Version:** [e.g. 1.0, 1.1]

**Language & Region:** [e.g. English & USA]

**Comment by JourneyOver** [comment]
1. Didn't fill out any info

2. I don't support citra in any form, so can't say if codes will work or not for games being run on citra.

Issue is being closed for both not filling out the issue template and for the fact I don't support citra.

**Comment by hyunzdk** [comment]
see sorry but all cheats  that i using here at citra work just this game that don't work,

**Comment by JourneyOver** [comment]
Well as I said codes may or may not work for citra, there's always that chance you'll run into something that doesn't work for whatever reason same as running into stuff that does.. the only time codes are removed/updated/fixed though is if they don't work on the actual 3DS system not an emulator.
