### ISSUE TITLE
I'm a new guy and I want need some help

### ISSUE THREAD

**Issue by SGlace** [JourneyOver/CTRPF-AR-CHEAT-CODES#57]
Can you make a video on youtube ? I'm a new guy to play 3ds.

I tried too many times. My New 3ds system is 11.8 and put ActionReplay to many folder . I can't use .txt to cheat the game.

Thanks!

**Comment by JourneyOver** [comment]
No 

1. I don't have a computer or anything to do such a thing.

2. Instructions are so simple that a baby could follow them.
