### ISSUE TITLE
monster hunter XX 

### ISSUE THREAD

**Issue by renaissance18** [JourneyOver/CTRPF-AR-CHEAT-CODES#58]
can you upload cheats for monster hunter XX version 1.4.0

**Comment by JourneyOver** [comment]
If you can point me in a direction where there are some then I gladly will..

**Comment by renaissance18** [comment]
you had cheats for monster hunter XX version 1.2.0, but i cant seem to find one for version 1.4.0, i thought you had the latest cheats for it

**Comment by JourneyOver** [comment]
No I don't have cheats for it.

1. I don't create any cheats, 99% of all cheats in the database came from fort42 before it shut down, and then the other 1% are from either PR's here or the sharkive repository.

2. I don't really have time much anymore to actively search for people posting cheats in random forums and such, so I pretty much rely on people to send PR's for new cheats right now.

if you don't have any codes nor can find any then I guess I will close this issue.

**Comment by renaissance18** [comment]
i see, ok thanks
