### ISSUE TITLE
Yo-kai Watch Cheats do not work.

### ISSUE THREAD

**Issue by RJWJ186** [JourneyOver/CTRPF-AR-CHEAT-CODES#63]
## Checklist:

- [x] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [ ] Other

## Description
 The Yo-kai Watch Cheats for USA
do not work. 
## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [e.g. New 3DS, Old 3DS, 2DS] New 3DS

**3DS Firmware Version:** [e.g. 11.6.0-39E]

**Method Used:** [e.g. LUMAS3DS 9.0 Plugin Loader, BOOTNTR]

**Game Version:** [e.g. 1.0, 1.1] Vr. 1.2

**Language & Region:** [e.g. English & USA]

**Comment by JourneyOver** [comment]
https://github.com/FlagBrew/Sharkive/issues/129#issuecomment-465739552 (Just a reminder to myself to update cheat names to mention they are for 1.0)
