### ISSUE TITLE
Pokemon X Shiny wild encounter issue. 

### ISSUE THREAD

**Issue by IvoryGrill** [JourneyOver/CTRPF-AR-CHEAT-CODES#66]
## Checklist:

- [x ] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [ ] Other

## Description

pokemon x , shiny wild encounter; when i attempt to use the cheat, nothing happens. yet your max money cheat works perfectly fine. 
## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [e.g. New 3DS, Old 3DS, 2DS]

**3DS Firmware Version:** [e.g. 11.6.0-39E]

**Method Used:** [e.g. LUMAS3DS 9.0 Plugin Loader, BOOTNTR]

**Game Version:** [e.g. 1.0, 1.1]

**Language & Region:** [e.g. English & USA]

**Comment by JourneyOver** [comment]
Please fill out "Extra Information" section, otherwise issue will be closed!

**Comment by JourneyOver** [comment]
Closed due to inactivity.
