### ISSUE TITLE
Moonjump and speedhack not working for Ocarina of Time 3D (Working moonjump - see comment)

### ISSUE THREAD

**Issue by ghost** [JourneyOver/CTRPF-AR-CHEAT-CODES#67]
## Checklist:

- [x] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [ ] Other

## Description

So, I downloaded GateShark cheats with Sharkive for OoT3D, enabled some cheat codes (infinite arrows) that work fine, but moonjump and 'move fast' don't work, I even tried on Citra. The [NTR cheat plugin one](https://gbatemp.net/threads/zelda-oot-cheats-plugin.422574/) works, could you convert these as GateShark?

## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [New 3DS XL]

**3DS Firmware Version:** [11.9.0-42E]

**Method Used:** [Rosalina menu / Citra cheats manager]

**Game Version:** [1.0]

**Language & Region:** [English & EUR]

**Comment by JourneyOver** [comment]
Sadly I don't really know anything on how to convert NTR stuff to gateshark, but I'm sure you could ask on gbatemp as iirc there are threads on there that you can request someone to convert ntr plugins to gateshark as long as the ntr plugin is open source. If you get someone to convert the plugin feel free to open a PR and I will gladly merge it in, otherwise I will just remove the two codes when I have time.

**Comment by ghost** [comment]
@JourneyOver Alright, I've got few buddies on discord who know about NTR and GateShark, I'll ask them there. I'd say keep the cheats instead removing, it may work on GateWay and is probably just an issue with Rosalina/Citra, I guess.

**Comment by ghost** [comment]
@JourneyOver Here's a working moonjump cheat. Thanks to @DarkFlare69 for converting it for me. You can add it.

[Moon Jump (Hold A)]
DD000000 00000001
D3000000 00000000
B05A2E3C 00000000
10000077 0000CB40
D2000000 00000000


Edit: For some reason, it works only on Citra, this cheat code doesn't work on Rosalina :/

**Comment by JourneyOver** [comment]
Thanks, will replace it soon.

**Comment by JourneyOver** [comment]
Okay well thanks for the edit on saying it only works for Citra
