### ISSUE TITLE
 Mario & Luigi: Bowser's Inside Story + Bowser Jr.'s Journey(usa)

### ISSUE THREAD

**Issue by draco25812** [JourneyOver/CTRPF-AR-CHEAT-CODES#68]
## Checklist:

- [ ] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [x] Other 

## Description
game has been updated to 1.2 but cheats are for 1.1

## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [e.g. New 3DS, Old 3DS, 2DS]

**3DS Firmware Version:** [e.g. 11.6.0-39E]

**Method Used:** [e.g. LUMAS3DS 9.0 Plugin Loader, BOOTNTR]

**Game Version:** 1.2

**Language & Region:** [e.g. English & USA]

**Comment by JourneyOver** [comment]
I do not make cheat codes, and I don't really have time to sit around anymore looking for cheat codes much anymore so if you are able to find/create codes that work you are free to either submit a PR with said updated codes, or if you find codes then you can throw up a link and I will update the codes when I can.
