### ISSUE TITLE
Code not working 

### ISSUE THREAD

**Issue by Alanahma123** [JourneyOver/CTRPF-AR-CHEAT-CODES#69]
## Checklist:

- [ x] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [! ] Other

## Description
Pokémon Omega Ruby’s Shiny cheat is not working has red marking when I press a on it and other codes appear red while trying enable them pls help also the Catch trainer Pokémon 

## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [Old 3DS]

**3DS Firmware Version:** [sys 11.9.0-40U]

**Method Used:** [LUMAS3DS 9.0 Plugin Loader, Sharkive]

**Game Version:** [1.4]

**Language & Region:** [ English & USA]

**Comment by JourneyOver** [comment]
How can I help with anything if you don't even mention what game it is that you are playing??

**Comment by Alanahma123** [comment]
Oof sorry Omega Ruby

**Comment by Alanahma123** [comment]
Pokémon Omega Ruby sorry again

**Comment by JourneyOver** [comment]
Can you please list the codes (the full code name) that aren't working like such
```
* code 1
* code 2
* ...
```

**Comment by Alanahma123** [comment]
* Shiny wild Pokémon press L and start to use
* Catch Trainers pokemon
* 100% catch rate
* Use PC anywhere
* Quick egg hatch
That’s about all I can remember testing out

**Comment by raember** [comment]
I didn't test them, but did you try out their individual triggers(those **not** mentioned in the caption)?
- `100% Catch rate` requires the user to press SELECT and UP and presumably doesn't work on 1.4(`100%Catch v1.4` doesn't have such a trigger).
- `Access the PC from anywhere v1.4` requires the user to press L.

Then there's the version issue: You use 1.4, but usually the cheats without a version number were made for 1.0. Like you listed `100% Catch rate` and `Quick Egg Hatching`, but there are 1.4 versions of them available: `100%Catch v1.4` and `Egg Instant Hatch v1.4`. Did you try those?

**Comment by Alanahma123** [comment]
Whenever I select those codes they always appear red, even individually they didnt work I’ll see if the 1.4v codes you mentioned work today, thanks

**Comment by Alanahma123** [comment]
Ok out of all v1.4 codes I tested the quick messages worked but the 100% catch rate, catch trainers Pokémon, quick egg hatch, and shiny wild Pokémon all did not work on v1.4 and most had a red mark around them when trying to enable them on the Rosalina cheats menu

**Comment by JourneyOver** [comment]
Guys I hate to do this, but between this repository, me dealing with [sharkive](https://github.com/FlagBrew/Sharkive) stuff, work*, and just about a ton of other things IRL I am sadly thinking I am going to have to drop this repository (put it into archive mode basically) as I barely have time to do much work anymore on really anything. 

*main reason is I have a very hectic schedule right now and for the foreseeable future so it makes things a lot harder.

I may do one more small update, to just get rid of these broken codes and close this issue out and merge in the last PR that I have sitting, and then archive this repository. I am sorry for this but IRL has kinda just taken over to much at the moment, I may come back in the future if another repository/site hasn't come up that does things better and I actually start having time to work on multiples of things again.


I will still be around for flagbrew/sharkive (and the eventual merge of getting sharkive into implemented into checkpoint) so I'm not going to be completely gone, but I just won't be working on this repository anymore.
