### ISSUE TITLE
Unclear AR Code Types

### ISSUE THREAD

**Issue by raember** [JourneyOver/CTRPF-AR-CHEAT-CODES#73]
## Checklist:

- [ ] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [x] Other

## Description (Used for Multi-Region/Versioning/Wrong Game/Other)

I don't understand the code types under [Conditional mode](https://github.com/JourneyOver/CTRPF-AR-CHEAT-CODES/blob/master/ActionReplayCodeTypes.txt#L59) codes:
```
Conditional mode:
-----------------------
DFFFFFFF 00000000 - Conditional codes: value of address is compared to YYYY (immediate value)
DFFFFFFF 00000001 - Conditional codes: value of address is compared to active data register
DFFFFFFF 00000002 - Conditional codes: active data register is compared to YYYY (immediate value)
DFFFFFFF 00000003 - Conditional codes: active storage register is compared to YYYY (immediate value)
DFFFFFFF 00000004 - Conditional codes: active data register is compared to active storage register
```
The value of which address? The offset? Where's the immediate short value YYYY?

**Comment by JourneyOver** [comment]
This would be something Nanquitas would have to answer, as I do not make codes. You could probably get an answer asking here https://gbatemp.net/threads/ctrpluginframework-blank-plugin-now-with-action-replay.487729/ or here https://discord.gg/z4ZMh27 (Nanquitas's discord)
